# Generated by Django 5.2.4 on 2025-07-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField(max_length=11)),
                ('message', models.TextField()),
                ('title', models.CharField()),
                ('fullname', models.CharField()),
            ],
        ),
    ]
