# Generated by Django 5.2.4 on 2025-07-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visite',
            name='number',
            field=models.CharField(max_length=14),
        ),
    ]
