# Generated by Django 5.2.4 on 2025-07-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_visite_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
