# Generated by Django 5.2.4 on 2025-07-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_visite_slug_remove_visite_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='title',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visite',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='visite',
            name='subject',
            field=models.TextField(max_length=40),
        ),
    ]
