# Generated by Django 5.2.4 on 2025-07-31 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_visite_title_alter_visite_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visite',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
