# Generated by Django 5.2.4 on 2025-07-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_rename_fullname_visite_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visite',
            name='title',
            field=models.CharField(unique=True),
        ),
    ]
