# Generated by Django 5.2.4 on 2025-07-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_visite_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visite',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
