# Generated by Django 5.2.4 on 2025-07-31 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_visite_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visite',
        ),
    ]
