# Generated by Django 5.2.4 on 2025-07-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0010_delete_visite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=14)),
                ('message', models.TextField(max_length=500)),
                ('subject', models.TextField(max_length=40)),
                ('full_name', models.CharField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
