# Generated by Django 5.2.4 on 2025-08-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visite',
            options={'verbose_name': 'ملاقات', 'verbose_name_plural': 'ملاقات ها'},
        ),
        migrations.AlterField(
            model_name='visite',
            name='full_name',
            field=models.CharField(verbose_name='نام شخص'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='message',
            field=models.TextField(max_length=500, verbose_name='پیغام'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='number',
            field=models.CharField(max_length=14, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='subject',
            field=models.TextField(max_length=40, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ویلای مورد نظر'),
        ),
    ]
