# Generated by Django 5.2.4 on 2025-07-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='properties/')),
                ('bathroom', models.CharField(max_length=30)),
                ('bedrooms', models.CharField(max_length=30)),
                ('floor', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('parking', models.CharField(max_length=30)),
            ],
        ),
    ]
