# Generated by Django 5.2.4 on 2025-07-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_properties_city_properties_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='properties',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='properties',
            name='state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='properties',
            name='street',
            field=models.CharField(max_length=100),
        ),
    ]
