# Generated by Django 5.2.4 on 2025-07-25 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('contract', models.BooleanField(blank=True, default=True, null=True)),
                ('payment', models.CharField(blank=True, max_length=15, null=True)),
                ('safety', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='SingleProperty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SingleProperty', to='home.singleproperty'),
        ),
    ]
