# Generated by Django 5.2.4 on 2025-07-25 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_singleproperty_properties_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleproperty',
            name='contract',
        ),
    ]
