# Generated by Django 5.2.4 on 2025-07-27 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_singleproperty_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singleproperty',
            name='contract',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='singleproperty',
            name='payment',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='singleproperty',
            name='safety',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='singleproperty',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='home.properties')),
                ('penthouse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penthouse', to='home.properties')),
                ('villa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='villa', to='home.properties')),
            ],
        ),
    ]
