# Generated by Django 5.2.4 on 2025-07-27 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_category_apartment_alter_category_penthouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='categories',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='apartment',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='penthouse',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='villa',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
