# Generated by Django 5.2.4 on 2025-07-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_properties_categories_alter_category_apartment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='apartment',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='penthouse',
        ),
        migrations.RemoveField(
            model_name='category',
            name='villa',
        ),
        migrations.AddField(
            model_name='category',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
