# Generated by Django 5.2.4 on 2025-07-27 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_apartment_category_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='home.category'),
        ),
    ]
