# Generated by Django 5.2.4 on 2025-07-27 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_properties_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='categories',
        ),
        migrations.AddField(
            model_name='properties',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='home.category'),
        ),
    ]
