# Generated by Django 5.2.4 on 2025-07-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_properties_categories_properties_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
