# Generated by Django 5.2.4 on 2025-07-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_singleproperty_properties_sing_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='properties',
            name='img_category',
            field=models.ImageField(default=1, upload_to='category/'),
            preserve_default=False,
        ),
    ]
