# Generated by Django 5.2.4 on 2025-08-01 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_category_image_properties_img_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='روز ارسال'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='نام شخص'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='پیغام'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='about',
            field=models.TextField(verbose_name='درباره دسته'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='bathroom',
            field=models.CharField(max_length=30, verbose_name='اتاق'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='bedrooms',
            field=models.CharField(max_length=30, verbose_name='سالن'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='home.category', verbose_name='دسته'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='city',
            field=models.CharField(max_length=50, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='floor',
            field=models.CharField(max_length=30, verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='image',
            field=models.ImageField(upload_to='properties/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='img_category',
            field=models.ImageField(upload_to='category/', verbose_name='عکس دسته'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='پلاک'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='sing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SingleProperty', to='home.singleproperty', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='properties',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='طوظیحات قرارداد و امنیت'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='state',
            field=models.CharField(max_length=20, verbose_name='کوچه'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='street',
            field=models.CharField(max_length=100, verbose_name='خیابان'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان'),
        ),
    ]
