# Generated by Django 5.2.4 on 2025-08-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_contact_date_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='property_like',
            field=models.BooleanField(default=False),
        ),
    ]
