# Generated by Django 5.2.4 on 2025-08-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_properties_property_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=1, upload_to='Category/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='properties',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
