# Generated by Django 5.2.4 on 2025-08-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_category_img_alter_properties_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='img_category',
        ),
    ]
